language: python
python:
    #    - "2.6" #unittest.skip N/A in py2.6
    - "2.7"

services:
    - rabbitmq

install:
    - pip install -r requirements.txt

beforescript:
    - 

script:
    - nosetests -v
    - bash integration-test.sh -t

notifications:
    email: ffledgling+travis@gmail.com
    irc: irc.mozilla.org#ffledgling
