language: python
python:
    #    - "2.6" #unittest.skip N/A in py2.6
    - "2.7"

os:
    - linux

services:
    - rabbitmq

install:
    #- pip install -r requirements.txt
    - python setup.py develop

before_script:
# Much needed InnoDB and MySQL configuration
#   Add innoDB fileformat, large_prefix and file_per_table
    - sudo sed -i 's/\(\* InnoDB\)/\1\ninnodb_file_format = Barracuda\ninnodb_large_prefix = 1\ninnodb_file_per_table=true/' /etc/mysql/my.cnf 
#   increase default timeout on travis from 180 to 1800 seconds (breaks connections)
    - sudo sed -i 's/\(wait_timeout\s\+= \).*/\1 1800/' /etc/mysql/my.cnf
    - cat /etc/mysql/my.cnf
    - sudo service mysql restart
      #- mysql -e 'show variables;'
      - mysql -e 'create database funsize_test;'
      #- mysql --help
      #- exit 1

script:
    - nosetests -v
    - bash tests/integration-test.sh -t

notifications:
    email: ffledgling+travis@gmail.com
    irc: irc.mozilla.org#ffledgling
