language: python
python:
    #    - "2.6" #unittest.skip N/A in py2.6
    - "2.7"

os:
    - linux

services:
    - rabbitmq

install:
    #- pip install -r requirements.txt
    - python setup.py develop

before_script:

script:
    - pwd
    - sudo ls
    - who
    - groups
    - sudo service mysql stop
    - sudo rm /etc/mysql/my.cnf
    - sudo wget people.mozilla.org/~asingh/my.cnf -O /home/travis/my.cnf
    - sudo service mysql start
    - mysql -e 'create database funsize_test;'
    - mysql --print-defaults
    - mysql --help
      #- exit 1
    - nosetests -v
    - bash tests/integration-test.sh -t

notifications:
    email: ffledgling+travis@gmail.com
    irc: irc.mozilla.org#ffledgling
