language: python
python:
    #    - "2.6" #unittest.skip N/A in py2.6
    - "2.7"

os:
    - linux

services:
    - rabbitmq

install:
    #- pip install -r requirements.txt
    - python setup.py develop

before_script:
    - mysql -e 'set global innodb_file_format=Barracuda'
    - mysql -e 'set global innodb_large_prefix=1'
    - mysql -e 'create database funsize_test;'

script:
    - nosetests -v
    - bash tests/integration-test.sh -t

notifications:
    email: ffledgling+travis@gmail.com
    irc: irc.mozilla.org#ffledgling
